# Name of the Pipeline
name: Stage Pipeline

# Define Trigger
on:
  push:
    branches:
      - master

# Jobs
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest

    # Steps
    steps:
    # Step 1 - Checkout
    - name: checkout
      uses: actions/checkout@v2

    # Step 2 - SSH into server and run script
    - name: ssh into server and run bash script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          /bin/bash -c "$(curl -sL https://raw.nt.com/KCuppens/installation-script/master/install.sh)"
          cd ${{ secrets.REPO_PATH }} && git pull origin ${{ secrets.BRANCH_NAME }}

